blank_issues_enabled: false
contact_links:
  - name: Questions and ideas
    url: https://github.com/endvater/open-regtech-academy/discussions
    about: Bitte nutze Discussions fuer offene Fragen und groessere Ideen.
